### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [ngxs/cli#1]
Hi,

when I launch 
`npm i @ngxs/cli -g`

I receive

> npm ERR! code E404
> npm ERR! 404 Not Found: @ngxs/cli@latest

**Comment by splincode** [comment]
We are waiting for us to publish a package
Soon we'll fix everything

**Comment by splincode** [comment]
current workaround:

```
$ git clone https://github.com/ngxs/cli.git
$ cd cli
$ npm link
```

Now you can use everywhere

```
$ ngxs
```

**Comment by markwhitfeld** [comment]
Package is published, it should be working now.

**Comment by AdaskoTheBeAsT** [comment]
Thanks! :)
