### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by mrs-cp** [ngxs/cli#13]
@splincode We would be very grateful if you could publish the latest changes to npm, since we cannot use the client currently due to a high risk warning re  the `glob-parent` version used by node-plop. 

![Bildschirmfoto 2023-11-06 um 10 47 13](https://github.com/ngxs/cli/assets/86765707/6cb8103e-d1c4-461e-bbbd-e6856d1ce600)

Thanks in advance. 💐

**Comment by splincode** [comment]
Released
